Global:
  use_gpu: true
  epoch_num: 200
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/r34_vd_inference_ctc/
  save_epoch_step: 1
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model: ./output/rec/r34_vd_inference_ctc/latest
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words_en/word_10.png
  # for data or label process
  character_dict_path: ./ppocr/utils/ppocr_keys_v1.txt
  max_text_length: 40
  infer_mode: False
  use_space_char: False
  save_res_path: ./output/rec/predicts_r34_vd_none_bilstm_ctc.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.05
  regularizer:
    name: 'L2'
    factor: 0

Architecture:
  model_type: rec
  algorithm: LSTR
  Transform:
  Backbone:
    name: ResNet
    layers: 34
  Neck:
    name: inference
    encoder_type: attention
    hidden_size: 256
  Head:
    name: CTCHead
    fc_decay: 0.004

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset: 
    name: SimpleDataSet        
    data_dir: ./train_data/trainImage 
    label_file_list:  ./train_data/fileTrainLabel.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 64 #256
    drop_last: True
    num_workers: 8 #8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./test_data/testImage
    label_file_list: ./test_data/fileTestLabel.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 16
    num_workers: 1
